### ISSUE TITLE
Write pro-tips about point and tooltip in documentation

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#32]
Points, especially the enlarged ones, are not very easy to mouseover. You have to put mouse on the edge of a point to see the tooltip. 
![point](https://cloud.githubusercontent.com/assets/822034/14392545/b6fccfbc-fd76-11e5-9057-1ffb9ab1e2a5.png)

In this example I think it's better to use solid marks because they are easier to mouseover:
![bin1](https://cloud.githubusercontent.com/assets/822034/14392664/527401a4-fd77-11e5-8913-262f4f2dce71.png)

On the other hand, when marks overlap with each other, hover on edge actually works well. In the example below, hover on edge allows more marks to be picked up.
![bin3point](https://cloud.githubusercontent.com/assets/822034/14392986/3eecb3e0-fd79-11e5-993e-7bebab948e7f.png)

**Comment by kanitw** [comment]
I think these are valid concerns that can be fixed by modifying the
visualization.

I think we should just write a section in the tooltip tutorial suggesting
how users can write specs that works well with tooltip (or throw warnings).

But we can t really make automatically intervention without potentially
introducing more errors.

**Comment by ZeningQu** [comment]
Close! This is PR #37
